INSERT INTO public.allergens (id, name)
VALUES
    ('1', 'Peanuts'),
    ('2', 'Tree nuts'),
    ('3', 'Soy'),
    ('4', 'Soy sauce'),
    ('5', 'Miso'),
    ('6', 'Tofu'),
    ('7', 'Chicken'),
    ('8', 'Beef'),
    ('9', 'Pork'),
    ('10', 'Fish'),
    ('11', 'Tilapia'),
    ('12', 'Bangus'),
    ('13', 'Shellfish'),
    ('14', 'Shrimp'),
    ('15', 'Prawns'),
    ('16', 'Mussels'),
    ('17', 'Squid'),
    ('18', 'Egg'),
    ('19', 'Wheat'),
    ('20', 'Gluten'),
    ('21', 'Noodles'),
    ('22', 'Wrappers'),
    ('23', 'Breadcrumbs'),
    ('24', 'Flour'),
    ('25', 'Dairy'),
    ('26', 'Milk'),
    ('27', 'Condensed milk'),
    ('28', 'Cream'),
    ('29', 'Butter'),
    ('30', 'Coconut'),
    ('31', 'Corn'),
    ('32', 'Liver')
ON CONFLICT (id) DO NOTHING;
